### PR TITLE
Upgrade to v0.7.11

### PR DESCRIPTION
**Pull request by johnBartos**
### What does this Pull Request do?
Upgrades hls.js to v0.7.10

### Why is this Pull Request needed?
Various bugfixes, improvements, and features

### Are there any points in the code the reviewer needs to double check?
Nothing specific, but we need to make sure that we're not loosing any features we haven't upstreamed

### Are there any Pull Requests open in other repos which need to be merged with this?
No

#### Addresses Issue(s):

JW7-4399

### CODE REVIEW

**Comment by robwalch** [comment]
@johnBartos lint errors?
https://jenkins.jwplayer.com/job/jw7-pr-builder-hlsjs/201/console

**Comment by johnBartos** [comment]
test this please

**Comment by dannyfinks** [comment]
test this please

**Comment by robwalch** [comment]
Waiting for https://jenkins.jwplayer.com/job/jw7-commercial-cucumber/7314/console

**Pull request merged**
