### PR TITLE
Merge 0.6.13

### PR DESCRIPTION
**Pull request by johnBartos**

### CODE REVIEW

**Comment by mangui** [comment]
huge :)

**Comment by johnBartos** [comment]
@mangui Some great changes! I'm fixing some bad merges but check out yours/ours diff:

https://github.com/dailymotion/hls.js/compare/master...jwplayer:feature/merge-0.6.12

We have v4 subtitles working well in most use cases but it relies on the player remaking video tags between streams.

**Comment by mangui** [comment]
Great. A bunch of changes but seems safe regression wise. Apart from some in the demuxer/probing ?

**Comment by mangui** [comment]
I guess you should have issues with some specific streams.

**Comment by robwalch** [comment]
@johnBartos I'm seeing a few other updates in this comparison https://github.com/jwplayer/hls.js/compare/master...dailymotion:v0.6.12

**Pull request closed without merging**
